export const APARTMENTS = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Skyline Luxury Suite",
    description: "Discover the epitome of contemporary living in the heart of Mumbai's business district.",
    price: "₹3.85 Cr",
    beds: 3,
    baths: 3,
    sqft: "2,450",
    location: "Worli, Mumbai",
    status: "Ready to Move"
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Urban Zen Penthouse",
    description: "Experience the perfect blend of sophistication and tranquil living with panoramic city views.",
    price: "₹5.12 Cr",
    beds: 4,
    baths: 4,
    sqft: "3,200",
    location: "Bandra West, Mumbai",
    status: "Ready to Move"
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Heritage District Loft",
    description: "Industrial chic loft with high ceilings and authentic exposed brickwork in the historic district.",
    price: "₹1.95 Cr",
    beds: 2,
    baths: 2,
    sqft: "1,550",
    location: "Colaba, Mumbai",
    status: "Available"
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Green Terrace Flat",
    description: "A serene ground-floor apartment with a private landscaped garden terrace and smart home features.",
    price: "₹2.45 Cr",
    beds: 2,
    baths: 2,
    sqft: "1,800",
    location: "Gachibowli, Hyderabad",
    status: "Under Construction"
  },
  {
    id: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT80Zu289yOLpfsXQlAb6o_gIGMk20DdH5OCA&s",
    category: "APARTMENT",
    title: "Executive Smart Studio",
    description: "Perfect for the modern professional, featuring full automation and concierge services.",
    price: "₹95 Lakh",
    beds: 1,
    baths: 1,
    sqft: "750",
    location: "Hitech City, Hyderabad",
    status: "Available"
  },
  {
    id: 6,
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Lakeside View Residence",
    description: "Tranquil living with stunning views of the Hussain Sagar lake and premium amenities.",
    price: "₹4.20 Cr",
    beds: 3,
    baths: 3,
    sqft: "2,800",
    location: "Banjara Hills, Hyderabad",
    status: "Ready to Move"
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Royal Heritage Suite",
    description: "Classic architecture meets modern convenience in this ultra-premium heritage restoration.",
    price: "₹8.50 Cr",
    beds: 4,
    baths: 5,
    sqft: "4,500",
    location: "Lutyens, Delhi",
    status: "Limited Edition"
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&q=80&w=1000",
    category: "APARTMENT",
    title: "Cyber City High-Rise",
    description: "Sleek glass-walled apartment with automated climate control and private elevator access.",
    price: "₹2.75 Cr",
    beds: 2,
    baths: 2,
    sqft: "1,900",
    location: "DLF Phase 5, Gurgaon",
    status: "Ready to Move"
  }
];
